id: A4C45C53B
title: 'MSV 1,01: Pravrajyāvastu'
type: translation
pechas:
- IA3DC8830
- IE63A3883
source_metadata:
  languages:
  - sa
  - bo
  datatype: PlainText
  created_at: 2023-02-09 15:01:06.921015
  last_modified_at: 2023-02-09 15:01:06.921028
alignment_to_base:
  IA3DC8830/A44B: 0DF0
  IE63A3883/8BB5: 0DF0
